language: node
addons:
  sauce_connect: true
install:
  - npm install
before_script:
  // This is our server
  - npm start &
script:
  - nightwatch --config nightwatch.js --env saucelabs
  - pkill node
